### ISSUE TITLE
Need help decrypting files

### ISSUE THREAD

**Issue by VerstreuteSeele** [syseleven/nextcloud-tools#19]
Hey there!

A while ago I f**ed up my old install of nextcloud. (was running v20 or v21 when it died) and now I just saw your script and found a backup of the encrypted files which I made just in case I will ever find a way to decrypt.
So far so good, downloaded, entered all the config entries in the php and ran it, hoping for the best. However my issue is that in $datadir/user/files_encryption there is no folder called "OC_DEFAULT_MODULE" . the folder structure is "files_encryption/keys/files/example-folder/image.jpg/OC_DEFAULT_MODULE"

any ideas?

**Comment by yahesh** [comment]
@VerstreuteSeele Two questions:
1. Do you know with which major version you started to use the server-side encryption?
2. Could enable the debug log and provide an excerpt of the log so that I can see which steps work for your yet-unknown-to-me file structure and which steps don't work for you.
3. Could you tell me which files are located in the `files_encryption/keys/files/example-folder/image.jpg/OC_DEFAULT_MODULE` folder?

Maybe it's just yet another way that paths can look like. If that's the case, it could probably be supported, given that everything up to locating the filekeys works.

**Comment by VerstreuteSeele** [comment]
1. Sadly not 100% sure. it was either 19 or 20. pretty sure it was 20 tho
2. there really isnt alot. it immediately fails with the error saying OC_DEFAULT_MODULE doesnt exist and then returns a `COULD NOT DECRYPT ANY PRIVATE KEY`
3. theres a fileKey and a master_some-gibberish.shareKey
![image](https://user-images.githubusercontent.com/55334727/146649051-34bab7e3-9442-424f-be54-981a0f1b4c81.png)

**Comment by yahesh** [comment]
@VerstreuteSeele Until now what I see from your screenshots looks pretty normal. The problem seems to be that the actual encryption keys cannot be found. Given you folder names there should be one called `nextcloud_data/files_encryption/OC_DEFAULT_MODULE/`. Is that the case? And if that's the case then does it contain a file called `master_544ed1d2.privateKey`? That's the one we need. If that file does not exist then files cannot be decrypted. If it exists then probably a configuration value has not been set correctly.

**Comment by VerstreuteSeele** [comment]
that folder does not exist, no. Guessing there's absolutely no way of recovering this data then?

**Comment by yahesh** [comment]
Unfortunately, that folder contains the (encrypted) RSA private key that's needed to decrypt the `master_*.shareKey` which is in turn needed to decrypt the `filekey`. So as there's no fast way to break RSA: No, you probably won't get your files back unless you find a copy of that specific folder as well. I'm sorry to say so. :(

**Comment by VerstreuteSeele** [comment]
Oh well. Guess that means I can get rid of those 40gb of encrypted mess now. This happened quite a while ago and to be fair, it is my fault bc before resetting to set up the cloud properly again I only backed up what I thought I would need to eventually decrypt them in some way.

Shit happens. Luckily nobody used my cloud back then and by now I learned my lesson and perform regular backups of the entire thing. 

Thanks for the super quick responses tho 👍
