### ISSUE TITLE
Encrypted files in group folders?

### ISSUE THREAD

**Issue by patrickuhlmann** [syseleven/nextcloud-tools#23]
After updating from Nextcloud 20 to 24 I had some issues with encrypted files that could not be decrypted. I was able to decrypt most of the files of the users. However I can't encrypt any of the files in the group folders.

The information from nextcloud is quite misleading. I often read that group folders cannot be encrypted but I clearly see encrypted files there (start with HBEGIN:oc_encryption_module.... I am unsure now if there has been an error when I moved these files from a user folder to the group folder. I did so using the webinterface and it didn't indicate any problem.

When I checked your script, I saw that it fails because it is unable to determine $datafilename for the groupfolders. Unfortunately I also don't see any files_encryption folder there where the keys could be stored.

Do you know anything about the state of group folders and if they are supported to be encrypted? Is it possible that these files are just encrypted with the master key or the pubShare key and if so, any possibility to recover them?

**Comment by patrickuhlmann** [comment]
There are only a handful of important files. Is it possible trying to decrypt them manually using the master key with the command line?

**Comment by yahesh** [comment]
@patrickuhlmann 

> There are only a handful of important files. Is it possible trying to decrypt them manually using the master key with the command line?

Unfortunately, this is not possible. The encryption consists of three separate encryptions. There is additional key material stored on disk that is decrypted with the master key before the actual file gets decrypted. As long as this additional key material is missing, you cannot do much with just the master key.

> The information from nextcloud is quite misleading. I often read that group folders cannot be encrypted but I clearly see encrypted files there (start with HBEGIN:oc_encryption_module.... I am unsure now if there has been an error when I moved these files from a user folder to the group folder. I did so using the webinterface and it didn't indicate any problem.

It happened in the past that simpling moving files between folders broke them because Nextcloud [had broken logic](https://github.com/nextcloud/server/issues/16419). This was the actual starting point of this rescue toolset here.

> When I checked your script, I saw that it fails because it is unable to determine $datafilename for the groupfolders. Unfortunately I also don't see any files_encryption folder there where the keys could be stored.

Yeah, the parsing of the filenames is pretty strict so that unsupported file types break early.

> Do you know anything about the state of group folders and if they are supported to be encrypted? Is it possible that these files are just encrypted with the master key or the pubShare key and if so, any possibility to recover them?

I haven't yet had a look into group folders as [the maintainers themselves say that they cannot be encrypted](https://github.com/nextcloud/groupfolders/issues/912). Internally, instead of using group folders we have a central owner of all shared folders that then shares these folders with the corresponding groups, thus having the benefits of group folders without their drawbacks.

Regarding your relevant files: Typically, when "moving" files between different storages (e.g. different shared folders), Nextcloud doesn't really move them. Instead, Nextcloud copies the file to the new destination and deletes the old copy. So, if you are lucky, you might find the old versions of the encrypted files in your trash folder which you should be able to decrypt.

**Comment by patrickuhlmann** [comment]
Thanks for your answers and your tool which is very useful.

I was able to solve my problem by restoring the last backup before I moved the folder. In that backup the files where still in the user folder and the key material was present. After I decrypted the files I overrode the encrypted files in the group folder and then everything worked.

**Comment by yahesh** [comment]
@patrickuhlmann Happy to hear that you were able to get all your files back. :)
