### ISSUE TITLE
Not able to decrypt files

### ISSUE THREAD

**Issue by awhitworth06** [syseleven/nextcloud-tools#39]
When I run this script, I only get the following message:

"WARNING: EXTERNAL STORAGE  DOES NOT EXIST"

I do expect this warning, as I'm not using external storage.
I just have empty values set for it.

However, none of my files show up in my empty target folder.

I have the DATADIRECTORY parameter set to the path of my Nextcloud "/data" folder. It is a network path, but I do have full access to it from my machine.
I have the INSTANCEID and SECRET parameters set.
I tried both with and without the RECOVERY_PASSWORD set.

I'm currently on Nextcloud 25.
I'm running the script from my Windows 10 machine where I have PHP installed and setup as a PATH in my environment variables.
I have my target set to just an empty folder on my C:\drive on my local machine.

When I turn on debug mode, I get the following:

DEBUG: debug mode enabled
DEBUG: loaded private key for master_cb9e1b5c
DEBUG: loaded private key for pubShare_cb9e1b5c
WARNING: EXTERNAL STORAGE  DOES NOT EXIST
DEBUG: exiting

Not sure what else to try here. Any advice is appreciated.

**Comment by yahesh** [comment]
@awhitworth06 If you don't have external storages, then you can set the configuration line to `define("EXTERNAL_STORAGES", []);` to get rid of the warning, however, it's just a warning and doesn't lead to the termination of the script, only errors do that.

The script does not specifically take care of Windows path structures. My first assumption therefore would be that you maybe have provided the paths with backslashes (`\`). The script assumes that forward-slashes are used (`/`). So, whereever you entered paths (in the config and during the execution) I'd first of all ask you to reverse the slashes (so that `C:\foo\bar\` becomes `C:/foo/bar/`).

Unfortunately, I don't have a Windows system to test this myself.

**Comment by awhitworth06** [comment]
Switching from using the back slash to using the forward slash worked! Thank you so much!

**Comment by yahesh** [comment]
@awhitworth06 I'm happy to hear this. Will add some info to the documentation.
